frr version 8.4.4
frr defaults traditional
hostname server3-osism
log syslog informational
no ip forwarding
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 100003
 bgp router-id 10.10.0.122
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 neighbor data1 interface remote-as external
 neighbor data2 interface remote-as external
 !
 address-family ipv4 unicast
  redistribute connected route-map bgp_out
 exit-address-family
exit
!
route-map bgp_out permit 10
 match interface loopback0
exit
!
